import "@/styles/globals.css";
import { type Metadata } from "next";
import  { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { TRPCReactProvider } from "@/trpc/react";
import { GeistSans } from "geist/font/sans";



export const metadata: Metadata = {
  title: "GitCollab",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>  
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <TRPCReactProvider>{children}</TRPCReactProvider>
          </ThemeProvider>
        <Toaster richColors />
      </body>
    </html>
    </ClerkProvider>
  );
}
